version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: ubber-postgres
    environment:
      POSTGRES_USER: ubber
      POSTGRES_PASSWORD: ubber_pass
      POSTGRES_DB: ubberdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: ubber-redis
    ports:
      - '6379:6379'
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ubber-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

  minio:
    image: minio/minio
    container_name: ubber-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always

volumes:
  pgdata: